# Using official python runtime base image

# Set the application directory


# Install our requirements.txt


# Copy our code from the current folder to /app inside the container


# Make port 80 available for links and/or publish


# Define our command to be run when launching the container

