FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder

# Create a working directory

# Copy the .csproj file and restore

# Copy source files to the image

# Build the project

# Specify app image

# Specify working directory for this stage

# Tell Docker what command to run when our image is executed inside a container

# Copy the /out directory from the build stage into the runtime image